config/routes.rb
Rails.application.routes.draw do
  get 'booking/index'

  root to: 'landing#index'
  resources :charges
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :sessions
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/booking_controller.rb
class BookingController < ApplicationController
  def index
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    # Amount in cents
    @amount = 11

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Student customer',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/booking_helper.rb
module BookingHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/views/booking/index.html.erb
<head>
  <title>Schedule a Session with Jason</title>
</head>
<body>
  <div class="row even">
    <div class="col-md-3 left-side"></div>
    <div class="col-md-6">
      <h1>Schedule a Weekday Session</h1>
      <div class="schedule-container">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Time</th>
                    <th>Monday</th>
                    <th>Tuesday</th>
                    <th>Wednesday</th>
                    <th>Thursday</th>
                    <th>Friday</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>7:00pm</td>
                    <td>Book Button</td>
                    <td>Book Button</td>
                    <td>Book Button</td>
                    <td>Book Button</td>
                    <td>Book Button</td>
                </tr>
                <tr>
                    <td>8:00pm</td>
                    <td>Book Button</td>
                    <td>Book Button</td>
                    <td>Book Button</td>
                    <td>Book Button</td>
                    <td>Book Button</td>
                </tr>
                <tr>
                    <td>9:00pm</td>
                    <td>Book Button</td>
                    <td>Book Button</td>
                    <td>Book Button</td>
                    <td>Book Button</td>
                    <td>Book Button</td>
                </tr>
                <tr>
                    <td>10:00pm</td>
                    <td>Book Button</td>
                    <td>Book Button</td>
                    <td>Book Button</td>
                    <td>Book Button</td>
                    <td>Book Button</td>
                </tr>
                <tr>
                    <td>11:00pm</td>
                    <td>Book Button</td>
                    <td>Book Button</td>
                    <td>Book Button</td>
                    <td>Book Button</td>
                    <td>Book Button</td>
                </tr>
            </tbody>
        </table>
      </div>
    </div>
    <div class="col-md-3 right-side"></div>
  </div>
</body>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$0.11</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $.11</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="11"
          data-locale="auto">
            
  </script>
<% end %>

app/views/landing/index.html.erb
<head>
</head>
<body>
	<div class="row even"> 
		<div class="col-lg-3 col-md-3 left-side">
		</div>
		<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
			<h1>Are you losing admission to Harvard because your tutor cannot teach effectively?</h1>
			<p>Your private tutor has an Ivy league degree. <br>
				But are your test scores or English improving as much as they should be?<br>
				Is your progress measured and the lessons designed specifically for you?<br>
				Wouldn’t your chance to attend an elite school be greater if your tutor attended an elite school AND has proven professional experience teaching non-native English speakers?
			</p>
		</div>
		<div class="col-lg-3 col-md-3 right-side">
		</div>
	</div>
	<div class="row odd"> 
		<div class="col-md-3 left-side">
		</div>
		<div class="col-md-6 col-sm-12 col-xs-12">
				<h2>Eleven Education combines elite university experience with proven effective, data-driven instruction</h2>
				<p>I’ll use my instructional system based on years of experience helping non-native English language learners reach at least 2 grade levels ahead. Every subject: English, vocabulary, history is made of smaller, measurable components.<br><br>

				Imagine an experienced teacher targeting each component and focusing on your exact weaknesses using proven teaching methods. Each week, we’ll measure your progress and you’ll see proof of rapid improvement in the data.
				</p>
		</div>
		<div class="col-md-3 right-side">
		</div>
	</div>
	<div class="row even"> 
			<div class="col-lg-3 col-md-3 left-side">
			</div>
			<div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
					<h2>Who is Eleven Education for?</h2>
					<p>
						Eleven Education is for serious students seeking an highly effective teacher with experience applying to top schools. We believe that with hard work, anything is possible. This program is not for the lazy or uninterested. If you follow our instruction, we guarantee improvement or your money back.
					</p>
					<%= image_tag('sat-scores.jpeg', alt: 'jasons-sat', size: "460x370") %>
			</div>
			<div class="col-lg-3 col-md-3 right-side">
			</div>
	</div>
	<div class="row odd"> 
		<div class="col-md-3 left-side">
		</div>
		<div class="col-md-6 col-sm-12 col-xs-12">
			<h3>“At first I was uncertain that Eleven Education would be worth the the price...</h3>
			<p>
				I’ve seen cheaper tutors available who offer the same services. After trying one month with Jason, I regret wasting my time with other tutors. Jason’s experience as a teacher shows in his techniques I haven’t seen from other tutors. Jason is the only teacher I’ve seen with a data-driven system of teaching and the strong academic credentials to back it up. Every week, I have proof that I am actually improving! <br><br>
		
				After seeing my improvement, I can only say this: If you aren’t using Jason currently, you should be, because next year he’s going to be twice as expensive!"
			</p>
		</div>
		<div class="col-md-3 right-side">
		</div>
	</div>
	<div class="row even"> 
		<div class="col-md-3 left-side">
		</div>
		<div class="col-md-6 col-sm-12 col-xs-12">
			<h3>“Usually I find tutors hit and miss. Often, I don’t learn anything I couldn’t learn myself or don’t learn anything at all...</h3>
			<p>
				Sometimes the learning materials is good, but the teacher doesn't explain it in a way that makes sense. Jason really knows what it takes to learn English vocabulary and writing because he is an American-born English speaker and attended a top US university. He explained it in a way that Chinese teacher cannot.
				<br><br>
				Jason didn't just give me the answer, he taught me how to derive it myself. He breaks down everything and guides me through a way of thinking I can use for any problem.
				<br><br>
				I was confident in knowing that if I didn't find the lessons useful, I could get a full refund with no problem."
			</p>
		</div>
		<div class="col-md-3 right-side">
		</div>
	</div>
	<div class="row odd"> 
		<div class="col-md-3 left-side">
		</div>
		<div class="col-md-6 col-sm-12 col-xs-12">
			<h2>Services We Offer</h2>
			<p>
			Icons with text under: 
			- Spoken English language tutoring (all levels), 
			- English Vocabulary tutoring (all levels)
			- English Writing tutoring (all levels)
			- English Reading tutoring (all levels)
			- AP U.S. History tutoring
			- AP European History tutoring
			- AP Government tutoring
			- AP English literature tutoring
			- SAT Test Preparation tutoring
			- College Counseling
			- Social Skills in America: Making Friends
			- Personal Statement and Essay Development
			- Scholarship Application Development
			</p>
		</div>
		<div class="col-md-3 right-side">
		</div>
	</div>
	<div class="row even"> 
		<div class="col-md-3 left-side">
		</div>
		<div class="col-md-6 col-sm-12 col-xs-12">
			<h3>“If you suspect that your tutor doesn’t have the experience or skills of writing an effective personal statement or essay development, you need to hire Jason....</h3>
			<p>
				I know my even with high SAT scores and a high GPA, I could not get into my dream school if my personal statement is not unique or good enough. I need to make sure that the help I get comes from a person who has proof that he is a excellent writer. 

				<br><br>Jason has won multiple prestigious scholarships and a full ride to an elite college based on his writing ability. I’ve seen proof of his scholarship awards, high GPA, and high SAT scores so I feel confident trusting him to help me every part of my application."
			</p>
		</div>
		<div class="col-md-3 right-side">
		</div>
	</div>
	<div class="row odd"> 
		<div class="col-md-3 left-side">
		</div>
		<div class="col-md-6 col-sm-12 col-xs-12">
			<h3>“Jason is one of the few teachers I’ve met that truly cares about my success. He holds me accountable to the work and messages me back quickly when I have questions...</h3>
			<p>
				I was impressed with how quick Jason responds to my questions. He texts me often to make sure I was doing the work every day and understood the material.<br><br>

				I specifically liked how Jason motivated me to work my hardest with a fun system of prizes. I was happy to study hard because I knew my work was rewarded with prizes. He’s a positive person that makes me feel happy when I’m studying.<br><br>

 				I’d just like to add that I feel very good about the decision to go with Jason. I’ve learned a lot and continue to do so everyday.
			</p>
		</div>
		<div class="col-md-3 right-side">
		</div>
	</div>
	<div class="row even"> 
		<div class="col-md-3 left-side">
		</div>
		<div class="col-md-6 col-sm-12 col-xs-12">
			<h2>Our No-Risk Guarantee</h2>
			<p>
				Buying our lessons comes with no risk. If you ever want your money back for any reason, we want you to have it back.<br><br>

				If you didn't learn anything...<br>
				If you didn't get into the school you wanted to...<br>
				If you just don't think the lessons were worth it...<br>
				Email our CEO, Jason, to get a full refund.
				<br><br>
				We only want to keep your money if you think we really earned it.
			</p>
		</div>
		<div class="col-md-3 right-side">
		</div>
	</div>
	<div class="row odd"> 
		<div class="col-md-3 left-side">
		</div>
		<div class="col-md-6 col-sm-12 col-xs-12">
			<h2>How does it work?</h2>
			<p>
				You book a weekly schedule for 4 weeks. You can book as many open time slots as you’d like. We will meet on the same day(s) and time(s) for 4 consecutive weeks through Skype. Materials will be given to you online to complete. In-person sessions are also available if you're in the DC area.
				<br><br>
				<a href="../booking/index" class="btn btn-lg btn-block">Schedule lessons risk-free</a><br><br>
				<%= image_tag('jason.jpeg', alt: 'jason-head-shot', size: "190x190") %>
			</p>
		</div>
		<div class="col-md-3 right-side">
		</div>
	</div>
</body>

app/views/layouts/_header.html.erb
<style>
  h1 {
    font-size: 40px;
  }
</style>
<h1>
  <bold>ELEVEN EDUCATION</bold>
</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ElevenEd</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
      body {
        text-align: center;
      }

      .row {
        margin: 0px !important;
        width: 100%;
        display: inline-block;
        padding-top: 35px;
        padding-bottom: 35px;
      }

      a:link, a:visited {
          background-color: #5BC0DE;
          color: white;
          padding: 14px 25px;
          text-align: center;
          text-decoration: none;
          display: inline-block;
      }

      a:hover, a:active {
          background-color: #F7F7F7;
      }

      .even {
        background-color: #5BC0DE;
      }

      .even h1, .even p, .even h2, .even h3 {
        color: #FFFFFF;
      }

      .odd {
        background-color: #FFFFFF;
      }

      .odd h1, .odd p {
        color: "black";
      }
    </style>
  </head>

  <%= render "layouts/header" %>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>